global:
  postgresql:
    auth:
      postgresPassword: "postgres"
      username: "testuser"
      password: "testpass"
      database: "testdb"
auth:
  enablePostgresUser: true
  postgresPassword: "postgres"
  username: "testuser"
  password: "testpass"
  database: "testdb"